creation_rules:
  - path_regex: backend/\.env$
    input_type: dotenv
    output_type: dotenv
    # Llave pública del servidor ubun-ia (privada en /etc/dashboards-im/age.key)
    age: age127sdryg3ensw5t8fcuym5at4yep0a97pn99rsjwc70ult9mxvu8sk2t828
